name: Concurrency Handling

on:
  workflow_dispatch:

jobs:
  task-a-1:
    runs-on: ubuntu-latest
    concurrency: 
      group: a
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
  task-b-1:
    concurrency: 
      group: b
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
  task-a-2:
    runs-on: ubuntu-latest
    concurrency: 
      group: a
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
  task-b-2:
    runs-on: ubuntu-latest
    concurrency: 
      group: b
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
