name: Deploy to Various environments

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, ${{ vars.Message }}!
  deploy-test:
    runs-on: ubuntu-latest
    environment: Test
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, ${{ vars.Message }}!
  deploy-prod:
    runs-on: ubuntu-latest
    environment: Production
    needs: [deploy-dev, deploy-test]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, ${{ vars.Message }}!
