name: Deploy to Various environments

on:
  workflow_dispatch:

jobs:
  no-env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, ${{ vars.MESSAGE }}!
  deploy-dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, ${{ vars.MESSAGE }}!
  deploy-test:
    runs-on: ubuntu-latest
    environment: Test
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, ${{ vars.MESSAGE }}!
  deploy-prod:
    runs-on: ubuntu-latest
    environment: Production
    needs: [deploy-dev, deploy-test, no-env]
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, ${{ vars.MESSAGE }}!
      - name: Output secret
        run: echo The secret is ${{ secrets.EXAMPLE_SECRET }}
