name: Reusable Workflow

on:
  workflow_call:
    inputs:
      who-to-greet:
        type: string
        description: Tell me who to greet
        required: true
      time-of-day:
        type: string
        description: Tell me what time of day it is
        required: true
    secrets:
      some-secret:
        description: This is some secret
    
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    name: Greet ${{ inputs.who-to-greet }}
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Good ${{ inputs.time-of-day }}, ${{ inputs.who-to-greet }}!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo Here is the secret ${{ secrets.some-secret }}
          echo test, and deploy your project.
